# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc-puzzle.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpc-puzzle.proto',
  package='com.jayway.kday.grpc',
  syntax='proto3',
  serialized_options=_b('P\001'),
  serialized_pb=_b('\n\x11grpc-puzzle.proto\x12\x14\x63om.jayway.kday.grpc\"\x1d\n\x08YourName\x12\x11\n\tyour_name\x18\x01 \x01(\t\"(\n\x07\x43lueOne\x12\x0c\n\x04\x63lue\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"(\n\x07\x43lueTwo\x12\x0c\n\x04\x63lue\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"*\n\tClueThree\x12\x0c\n\x04\x63lue\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\")\n\x08\x43lueFour\x12\x0c\n\x04\x63lue\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x12\n\x03Key\x12\x0b\n\x03key\x18\x01 \x01(\t\"#\n\x0b\x46inalSecret\x12\x14\n\x0c\x66inal_secret\x18\x01 \x01(\t2\x8f\x03\n\x06Puzzle\x12J\n\tStartHere\x12\x1e.com.jayway.kday.grpc.YourName\x1a\x1d.com.jayway.kday.grpc.ClueOne\x12K\n\x0b\x65ndpointOne\x12\x1d.com.jayway.kday.grpc.ClueOne\x1a\x1d.com.jayway.kday.grpc.ClueTwo\x12M\n\x0b\x65ndpointTwo\x12\x1d.com.jayway.kday.grpc.ClueTwo\x1a\x1f.com.jayway.kday.grpc.ClueThree\x12P\n\rendpointThree\x12\x1f.com.jayway.kday.grpc.ClueThree\x1a\x1e.com.jayway.kday.grpc.ClueFour\x12K\n\x0bSolvePuzzle\x12\x19.com.jayway.kday.grpc.Key\x1a!.com.jayway.kday.grpc.FinalSecretB\x02P\x01\x62\x06proto3')
)




_YOURNAME = _descriptor.Descriptor(
  name='YourName',
  full_name='com.jayway.kday.grpc.YourName',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='your_name', full_name='com.jayway.kday.grpc.YourName.your_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=72,
)


_CLUEONE = _descriptor.Descriptor(
  name='ClueOne',
  full_name='com.jayway.kday.grpc.ClueOne',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clue', full_name='com.jayway.kday.grpc.ClueOne.clue', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='com.jayway.kday.grpc.ClueOne.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=114,
)


_CLUETWO = _descriptor.Descriptor(
  name='ClueTwo',
  full_name='com.jayway.kday.grpc.ClueTwo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clue', full_name='com.jayway.kday.grpc.ClueTwo.clue', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='com.jayway.kday.grpc.ClueTwo.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=156,
)


_CLUETHREE = _descriptor.Descriptor(
  name='ClueThree',
  full_name='com.jayway.kday.grpc.ClueThree',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clue', full_name='com.jayway.kday.grpc.ClueThree.clue', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='com.jayway.kday.grpc.ClueThree.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=200,
)


_CLUEFOUR = _descriptor.Descriptor(
  name='ClueFour',
  full_name='com.jayway.kday.grpc.ClueFour',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clue', full_name='com.jayway.kday.grpc.ClueFour.clue', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='com.jayway.kday.grpc.ClueFour.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=243,
)


_KEY = _descriptor.Descriptor(
  name='Key',
  full_name='com.jayway.kday.grpc.Key',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='com.jayway.kday.grpc.Key.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=245,
  serialized_end=263,
)


_FINALSECRET = _descriptor.Descriptor(
  name='FinalSecret',
  full_name='com.jayway.kday.grpc.FinalSecret',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='final_secret', full_name='com.jayway.kday.grpc.FinalSecret.final_secret', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=265,
  serialized_end=300,
)

DESCRIPTOR.message_types_by_name['YourName'] = _YOURNAME
DESCRIPTOR.message_types_by_name['ClueOne'] = _CLUEONE
DESCRIPTOR.message_types_by_name['ClueTwo'] = _CLUETWO
DESCRIPTOR.message_types_by_name['ClueThree'] = _CLUETHREE
DESCRIPTOR.message_types_by_name['ClueFour'] = _CLUEFOUR
DESCRIPTOR.message_types_by_name['Key'] = _KEY
DESCRIPTOR.message_types_by_name['FinalSecret'] = _FINALSECRET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

YourName = _reflection.GeneratedProtocolMessageType('YourName', (_message.Message,), {
  'DESCRIPTOR' : _YOURNAME,
  '__module__' : 'grpc_puzzle_pb2'
  # @@protoc_insertion_point(class_scope:com.jayway.kday.grpc.YourName)
  })
_sym_db.RegisterMessage(YourName)

ClueOne = _reflection.GeneratedProtocolMessageType('ClueOne', (_message.Message,), {
  'DESCRIPTOR' : _CLUEONE,
  '__module__' : 'grpc_puzzle_pb2'
  # @@protoc_insertion_point(class_scope:com.jayway.kday.grpc.ClueOne)
  })
_sym_db.RegisterMessage(ClueOne)

ClueTwo = _reflection.GeneratedProtocolMessageType('ClueTwo', (_message.Message,), {
  'DESCRIPTOR' : _CLUETWO,
  '__module__' : 'grpc_puzzle_pb2'
  # @@protoc_insertion_point(class_scope:com.jayway.kday.grpc.ClueTwo)
  })
_sym_db.RegisterMessage(ClueTwo)

ClueThree = _reflection.GeneratedProtocolMessageType('ClueThree', (_message.Message,), {
  'DESCRIPTOR' : _CLUETHREE,
  '__module__' : 'grpc_puzzle_pb2'
  # @@protoc_insertion_point(class_scope:com.jayway.kday.grpc.ClueThree)
  })
_sym_db.RegisterMessage(ClueThree)

ClueFour = _reflection.GeneratedProtocolMessageType('ClueFour', (_message.Message,), {
  'DESCRIPTOR' : _CLUEFOUR,
  '__module__' : 'grpc_puzzle_pb2'
  # @@protoc_insertion_point(class_scope:com.jayway.kday.grpc.ClueFour)
  })
_sym_db.RegisterMessage(ClueFour)

Key = _reflection.GeneratedProtocolMessageType('Key', (_message.Message,), {
  'DESCRIPTOR' : _KEY,
  '__module__' : 'grpc_puzzle_pb2'
  # @@protoc_insertion_point(class_scope:com.jayway.kday.grpc.Key)
  })
_sym_db.RegisterMessage(Key)

FinalSecret = _reflection.GeneratedProtocolMessageType('FinalSecret', (_message.Message,), {
  'DESCRIPTOR' : _FINALSECRET,
  '__module__' : 'grpc_puzzle_pb2'
  # @@protoc_insertion_point(class_scope:com.jayway.kday.grpc.FinalSecret)
  })
_sym_db.RegisterMessage(FinalSecret)


DESCRIPTOR._options = None

_PUZZLE = _descriptor.ServiceDescriptor(
  name='Puzzle',
  full_name='com.jayway.kday.grpc.Puzzle',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=303,
  serialized_end=702,
  methods=[
  _descriptor.MethodDescriptor(
    name='StartHere',
    full_name='com.jayway.kday.grpc.Puzzle.StartHere',
    index=0,
    containing_service=None,
    input_type=_YOURNAME,
    output_type=_CLUEONE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='endpointOne',
    full_name='com.jayway.kday.grpc.Puzzle.endpointOne',
    index=1,
    containing_service=None,
    input_type=_CLUEONE,
    output_type=_CLUETWO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='endpointTwo',
    full_name='com.jayway.kday.grpc.Puzzle.endpointTwo',
    index=2,
    containing_service=None,
    input_type=_CLUETWO,
    output_type=_CLUETHREE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='endpointThree',
    full_name='com.jayway.kday.grpc.Puzzle.endpointThree',
    index=3,
    containing_service=None,
    input_type=_CLUETHREE,
    output_type=_CLUEFOUR,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SolvePuzzle',
    full_name='com.jayway.kday.grpc.Puzzle.SolvePuzzle',
    index=4,
    containing_service=None,
    input_type=_KEY,
    output_type=_FINALSECRET,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PUZZLE)

DESCRIPTOR.services_by_name['Puzzle'] = _PUZZLE

# @@protoc_insertion_point(module_scope)
