// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.1
// source: grpc-puzzle.proto

package goexample

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type YourName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	YourName string `protobuf:"bytes,1,opt,name=your_name,json=yourName,proto3" json:"your_name,omitempty"`
}

func (x *YourName) Reset() {
	*x = YourName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_puzzle_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *YourName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YourName) ProtoMessage() {}

func (x *YourName) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_puzzle_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YourName.ProtoReflect.Descriptor instead.
func (*YourName) Descriptor() ([]byte, []int) {
	return file_grpc_puzzle_proto_rawDescGZIP(), []int{0}
}

func (x *YourName) GetYourName() string {
	if x != nil {
		return x.YourName
	}
	return ""
}

type ClueOne struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Clue    string `protobuf:"bytes,1,opt,name=clue,proto3" json:"clue,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ClueOne) Reset() {
	*x = ClueOne{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_puzzle_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClueOne) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClueOne) ProtoMessage() {}

func (x *ClueOne) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_puzzle_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClueOne.ProtoReflect.Descriptor instead.
func (*ClueOne) Descriptor() ([]byte, []int) {
	return file_grpc_puzzle_proto_rawDescGZIP(), []int{1}
}

func (x *ClueOne) GetClue() string {
	if x != nil {
		return x.Clue
	}
	return ""
}

func (x *ClueOne) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ClueTwo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Clue    string `protobuf:"bytes,1,opt,name=clue,proto3" json:"clue,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ClueTwo) Reset() {
	*x = ClueTwo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_puzzle_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClueTwo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClueTwo) ProtoMessage() {}

func (x *ClueTwo) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_puzzle_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClueTwo.ProtoReflect.Descriptor instead.
func (*ClueTwo) Descriptor() ([]byte, []int) {
	return file_grpc_puzzle_proto_rawDescGZIP(), []int{2}
}

func (x *ClueTwo) GetClue() string {
	if x != nil {
		return x.Clue
	}
	return ""
}

func (x *ClueTwo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ClueThree struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Clue    string `protobuf:"bytes,1,opt,name=clue,proto3" json:"clue,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ClueThree) Reset() {
	*x = ClueThree{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_puzzle_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClueThree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClueThree) ProtoMessage() {}

func (x *ClueThree) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_puzzle_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClueThree.ProtoReflect.Descriptor instead.
func (*ClueThree) Descriptor() ([]byte, []int) {
	return file_grpc_puzzle_proto_rawDescGZIP(), []int{3}
}

func (x *ClueThree) GetClue() string {
	if x != nil {
		return x.Clue
	}
	return ""
}

func (x *ClueThree) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ClueFour struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Clue    string `protobuf:"bytes,1,opt,name=clue,proto3" json:"clue,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ClueFour) Reset() {
	*x = ClueFour{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_puzzle_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClueFour) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClueFour) ProtoMessage() {}

func (x *ClueFour) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_puzzle_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClueFour.ProtoReflect.Descriptor instead.
func (*ClueFour) Descriptor() ([]byte, []int) {
	return file_grpc_puzzle_proto_rawDescGZIP(), []int{4}
}

func (x *ClueFour) GetClue() string {
	if x != nil {
		return x.Clue
	}
	return ""
}

func (x *ClueFour) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Key struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *Key) Reset() {
	*x = Key{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_puzzle_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_puzzle_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_grpc_puzzle_proto_rawDescGZIP(), []int{5}
}

func (x *Key) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type FinalSecret struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FinalSecret string `protobuf:"bytes,1,opt,name=final_secret,json=finalSecret,proto3" json:"final_secret,omitempty"`
}

func (x *FinalSecret) Reset() {
	*x = FinalSecret{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_puzzle_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinalSecret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalSecret) ProtoMessage() {}

func (x *FinalSecret) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_puzzle_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalSecret.ProtoReflect.Descriptor instead.
func (*FinalSecret) Descriptor() ([]byte, []int) {
	return file_grpc_puzzle_proto_rawDescGZIP(), []int{6}
}

func (x *FinalSecret) GetFinalSecret() string {
	if x != nil {
		return x.FinalSecret
	}
	return ""
}

var File_grpc_puzzle_proto protoreflect.FileDescriptor

var file_grpc_puzzle_proto_rawDesc = []byte{
	0x0a, 0x11, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x70, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x14, 0x63, 0x6f, 0x6d, 0x2e, 0x6a, 0x61, 0x79, 0x77, 0x61, 0x79, 0x2e,
	0x6b, 0x64, 0x61, 0x79, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x22, 0x27, 0x0a, 0x08, 0x59, 0x6f, 0x75,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x79, 0x6f, 0x75, 0x72, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x79, 0x6f, 0x75, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0x37, 0x0a, 0x07, 0x43, 0x6c, 0x75, 0x65, 0x4f, 0x6e, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6c, 0x75,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x37, 0x0a, 0x07, 0x43,
	0x6c, 0x75, 0x65, 0x54, 0x77, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x39, 0x0a, 0x09, 0x43, 0x6c, 0x75, 0x65, 0x54, 0x68, 0x72, 0x65,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x63, 0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x38, 0x0a, 0x08, 0x43, 0x6c, 0x75, 0x65, 0x46, 0x6f, 0x75, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6c, 0x75, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x17, 0x0a, 0x03, 0x4b, 0x65, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x22, 0x30, 0x0a, 0x0b, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x53, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x73, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x53, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x32, 0x8f, 0x03, 0x0a, 0x06, 0x50, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x12,
	0x4a, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x48, 0x65, 0x72, 0x65, 0x12, 0x1e, 0x2e, 0x63,
	0x6f, 0x6d, 0x2e, 0x6a, 0x61, 0x79, 0x77, 0x61, 0x79, 0x2e, 0x6b, 0x64, 0x61, 0x79, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x59, 0x6f, 0x75, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x1d, 0x2e, 0x63,
	0x6f, 0x6d, 0x2e, 0x6a, 0x61, 0x79, 0x77, 0x61, 0x79, 0x2e, 0x6b, 0x64, 0x61, 0x79, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x43, 0x6c, 0x75, 0x65, 0x4f, 0x6e, 0x65, 0x12, 0x4b, 0x0a, 0x0b, 0x65,
	0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x4f, 0x6e, 0x65, 0x12, 0x1d, 0x2e, 0x63, 0x6f, 0x6d,
	0x2e, 0x6a, 0x61, 0x79, 0x77, 0x61, 0x79, 0x2e, 0x6b, 0x64, 0x61, 0x79, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x43, 0x6c, 0x75, 0x65, 0x4f, 0x6e, 0x65, 0x1a, 0x1d, 0x2e, 0x63, 0x6f, 0x6d, 0x2e,
	0x6a, 0x61, 0x79, 0x77, 0x61, 0x79, 0x2e, 0x6b, 0x64, 0x61, 0x79, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x43, 0x6c, 0x75, 0x65, 0x54, 0x77, 0x6f, 0x12, 0x4d, 0x0a, 0x0b, 0x65, 0x6e, 0x64, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x54, 0x77, 0x6f, 0x12, 0x1d, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x6a, 0x61,
	0x79, 0x77, 0x61, 0x79, 0x2e, 0x6b, 0x64, 0x61, 0x79, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43,
	0x6c, 0x75, 0x65, 0x54, 0x77, 0x6f, 0x1a, 0x1f, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x6a, 0x61, 0x79,
	0x77, 0x61, 0x79, 0x2e, 0x6b, 0x64, 0x61, 0x79, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x6c,
	0x75, 0x65, 0x54, 0x68, 0x72, 0x65, 0x65, 0x12, 0x50, 0x0a, 0x0d, 0x65, 0x6e, 0x64, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x54, 0x68, 0x72, 0x65, 0x65, 0x12, 0x1f, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x6a,
	0x61, 0x79, 0x77, 0x61, 0x79, 0x2e, 0x6b, 0x64, 0x61, 0x79, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x43, 0x6c, 0x75, 0x65, 0x54, 0x68, 0x72, 0x65, 0x65, 0x1a, 0x1e, 0x2e, 0x63, 0x6f, 0x6d, 0x2e,
	0x6a, 0x61, 0x79, 0x77, 0x61, 0x79, 0x2e, 0x6b, 0x64, 0x61, 0x79, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x43, 0x6c, 0x75, 0x65, 0x46, 0x6f, 0x75, 0x72, 0x12, 0x4b, 0x0a, 0x0b, 0x53, 0x6f, 0x6c,
	0x76, 0x65, 0x50, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x12, 0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x6a,
	0x61, 0x79, 0x77, 0x61, 0x79, 0x2e, 0x6b, 0x64, 0x61, 0x79, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x4b, 0x65, 0x79, 0x1a, 0x21, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x6a, 0x61, 0x79, 0x77, 0x61, 0x79,
	0x2e, 0x6b, 0x64, 0x61, 0x79, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x46, 0x69, 0x6e, 0x61, 0x6c,
	0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x42, 0x2c, 0x50, 0x01, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x50, 0x72, 0x65, 0x79, 0x66, 0x69, 0x78, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x2d, 0x70, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x2f, 0x67, 0x6f, 0x65, 0x78, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_puzzle_proto_rawDescOnce sync.Once
	file_grpc_puzzle_proto_rawDescData = file_grpc_puzzle_proto_rawDesc
)

func file_grpc_puzzle_proto_rawDescGZIP() []byte {
	file_grpc_puzzle_proto_rawDescOnce.Do(func() {
		file_grpc_puzzle_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_puzzle_proto_rawDescData)
	})
	return file_grpc_puzzle_proto_rawDescData
}

var file_grpc_puzzle_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_grpc_puzzle_proto_goTypes = []interface{}{
	(*YourName)(nil),    // 0: com.jayway.kday.grpc.YourName
	(*ClueOne)(nil),     // 1: com.jayway.kday.grpc.ClueOne
	(*ClueTwo)(nil),     // 2: com.jayway.kday.grpc.ClueTwo
	(*ClueThree)(nil),   // 3: com.jayway.kday.grpc.ClueThree
	(*ClueFour)(nil),    // 4: com.jayway.kday.grpc.ClueFour
	(*Key)(nil),         // 5: com.jayway.kday.grpc.Key
	(*FinalSecret)(nil), // 6: com.jayway.kday.grpc.FinalSecret
}
var file_grpc_puzzle_proto_depIdxs = []int32{
	0, // 0: com.jayway.kday.grpc.Puzzle.StartHere:input_type -> com.jayway.kday.grpc.YourName
	1, // 1: com.jayway.kday.grpc.Puzzle.endpointOne:input_type -> com.jayway.kday.grpc.ClueOne
	2, // 2: com.jayway.kday.grpc.Puzzle.endpointTwo:input_type -> com.jayway.kday.grpc.ClueTwo
	3, // 3: com.jayway.kday.grpc.Puzzle.endpointThree:input_type -> com.jayway.kday.grpc.ClueThree
	5, // 4: com.jayway.kday.grpc.Puzzle.SolvePuzzle:input_type -> com.jayway.kday.grpc.Key
	1, // 5: com.jayway.kday.grpc.Puzzle.StartHere:output_type -> com.jayway.kday.grpc.ClueOne
	2, // 6: com.jayway.kday.grpc.Puzzle.endpointOne:output_type -> com.jayway.kday.grpc.ClueTwo
	3, // 7: com.jayway.kday.grpc.Puzzle.endpointTwo:output_type -> com.jayway.kday.grpc.ClueThree
	4, // 8: com.jayway.kday.grpc.Puzzle.endpointThree:output_type -> com.jayway.kday.grpc.ClueFour
	6, // 9: com.jayway.kday.grpc.Puzzle.SolvePuzzle:output_type -> com.jayway.kday.grpc.FinalSecret
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_puzzle_proto_init() }
func file_grpc_puzzle_proto_init() {
	if File_grpc_puzzle_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_puzzle_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*YourName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_puzzle_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClueOne); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_puzzle_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClueTwo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_puzzle_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClueThree); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_puzzle_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClueFour); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_puzzle_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Key); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_puzzle_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinalSecret); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_puzzle_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_puzzle_proto_goTypes,
		DependencyIndexes: file_grpc_puzzle_proto_depIdxs,
		MessageInfos:      file_grpc_puzzle_proto_msgTypes,
	}.Build()
	File_grpc_puzzle_proto = out.File
	file_grpc_puzzle_proto_rawDesc = nil
	file_grpc_puzzle_proto_goTypes = nil
	file_grpc_puzzle_proto_depIdxs = nil
}
